#!/bin/bash

BOLD=$(tput bold)
NORMAL=$(tput sgr0)
BLACK=$(tput setaf 0)
RED=$(tput setaf 1)
RED_BG=$(tput setab 1)
GREEN=$(tput setaf 2)
GREEN_BG=$(tput setab 2)
WHITE=$(tput setaf 15)

TICK="[${GREEN}✓${NORMAL}]"
CROSS="[${RED}✗${NORMAL}]"

RANDOM=$$
SLEEP=1

function gen () {
  for (( i = 1; i <= $1; i++ )); do
    TEST=$(tr -dc A-Za-z0-9 </dev/urandom | head -c 4095)
    if [ ! -f ./tests/sendme_"$i" ]; then
      echo -n "$TEST" > ./tests/sendme_"$i"
    fi
  done

  if [ "$2" != "-s" ]; then
    echo "$1 Test creati"
  fi
}

function clean () {
  rm -f ./tests/*_out
  if [ "$1" != "-s" ]; then
    echo "Test out eliminati"
  fi
}

function delete () {
  rm -f ./tests/sendme_{1..2000}
  if [ "$1" != "-s" ]; then
    echo "Tutti i test sono stati eliminati"
  fi
}

if [[ "$*" == *"gen_more"* ]]; then
  gen 1000
elif [[ "$*" == *"gen_random"* ]]; then
  R=$((RANDOM % 130))
  gen $R
elif [[ "$*" == *"gen"* ]]; then
  gen 10
fi

if [[ "$*" == *"run"* ]]; then
  printf "\nLo script cicla ogni secondo e ricrea ogni volta un numero (da 1 a 130) di file sendme all'interno della cartella test, poi esegue il client utilizzando la cwd dello script come path.\n"
  printf "\n%sLo script può essere interrotto in qualsiasi momento con Ctrl-c%s\n" "${GREEN}" "${NORMAL}"
  printf "%s%sATTENZIONE: assicurati che il server sia in esecuzione correttamente e che esista la cartella test%s\n" "${BOLD}" "${RED}" "${NORMAL}"
  read -r -p "Vuoi procedere con i test? [y/N] " response
  if [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]
  then
    N=1
    echo ""
    while true; do
      delete -s
      clean -s
      R=$((RANDOM % 130))
      gen $R -s

      temp=$(./client_0 "$PWD" 2>&1)
      if [ $? -ne 0 ]; then
        printf "%sTEST %d %s\n\n%sExit message:%s\n%s\n" "${BOLD}" "${N}" "${CROSS}" "${BOLD}" "${NORMAL}" "${temp}" 
        exit 1
      else
        printf "%sTEST %d %s%s\n" "${BOLD}" "${N}" "${NORMAL}" "${TICK}"
      fi
      ((N++))
      sleep $SLEEP
    done
  fi
fi

if [[ "$*" ==  *"clean"* ]]; then
  clean
fi

if [[ "$*" == *"del"* ]]; then
  delete
fi